#ifndef BIGQUERY_VERSION_INFO_H_
#define BIGQUERY_VERSION_INFO_H_

#define BIGQUERY_CLIENT_VERSION_MAJOR 0
#define BIGQUERY_CLIENT_VERSION_MINOR 1
#define BIGQUERY_CLIENT_VERSION_PATCH 0

#endif  // BIGQUERY_VERSION_INFO_H_
